apiVersion: v1
kind: Service
metadata:
  name: firstctrservices
spec:
  selector:
    app: firstcontainerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort

