apiVersion: v1
kind: Pod
metadata:
  name: loginapp
spec:
  containers:
    - name: firstcontainer
      image: iftekar/hello:5000
      ports:
        - containerPort: 5000
      imagePullPolicy: Always

