apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstcontainerreplicas
  labels:
    app: firstcontainerapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: firstcontainerapp
  template:
    metadata:
      labels:
        app: firstcontainerapp
    spec:
      containers:
        - name: firstcontainer
          image: iftekar/hello:5000
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "myprojectdb"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"

